# coding: utf-8

"""
    CDR Banking API

    Consumer Data Standards APIs created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker to meet the needs of the Consumer Data Right

    The version of the OpenAPI document: 1.29.0
    Contact: contact@consumerdatastandards.gov.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class BankingAccountDetailV3AllOfFeaturesInner(BaseModel):
    """
    BankingAccountDetailV3AllOfFeaturesInner
    """ # noqa: E501
    feature_type: StrictStr = Field(description="The type of feature described", alias="featureType")
    additional_value: Optional[StrictStr] = Field(default=None, description="Generic field containing additional information relevant to the [featureType](#tocSproductfeaturetypedoc) specified. Whether mandatory or not is dependent on the value of the [featureType.](#tocSproductfeaturetypedoc)", alias="additionalValue")
    additional_info: Optional[StrictStr] = Field(default=None, description="Display text providing more information on the feature. Mandatory if the [feature type](#tocSproductfeaturetypedoc) is set to OTHER", alias="additionalInfo")
    additional_info_uri: Optional[StrictStr] = Field(default=None, description="Link to a web page with more information on this feature", alias="additionalInfoUri")
    is_activated: Optional[StrictBool] = Field(default=True, description="True if the feature is already activated and false if the feature is available for activation. Defaults to true if absent. (note this is an additional field appended to the feature object defined in the Product Reference payload)", alias="isActivated")
    __properties: ClassVar[List[str]] = ["featureType", "additionalValue", "additionalInfo", "additionalInfoUri", "isActivated"]

    @field_validator('feature_type')
    def feature_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ADDITIONAL_CARDS', 'BALANCE_TRANSFERS', 'BILL_PAYMENT', 'BONUS_REWARDS', 'CARD_ACCESS', 'CASHBACK_OFFER', 'COMPLEMENTARY_PRODUCT_DISCOUNTS', 'DIGITAL_BANKING', 'DIGITAL_WALLET', 'DONATE_INTEREST', 'EXTRA_REPAYMENTS', 'FRAUD_PROTECTION', 'FREE_TXNS', 'FREE_TXNS_ALLOWANCE', 'GUARANTOR', 'INSURANCE', 'INSTALMENT_PLAN', 'INTEREST_FREE', 'INTEREST_FREE_TRANSFERS', 'LOYALTY_PROGRAM', 'NOTIFICATIONS', 'NPP_ENABLED', 'NPP_PAYID', 'OFFSET', 'OTHER', 'OVERDRAFT', 'REDRAW', 'RELATIONSHIP_MANAGEMENT', 'UNLIMITED_TXNS']):
            raise ValueError("must be one of enum values ('ADDITIONAL_CARDS', 'BALANCE_TRANSFERS', 'BILL_PAYMENT', 'BONUS_REWARDS', 'CARD_ACCESS', 'CASHBACK_OFFER', 'COMPLEMENTARY_PRODUCT_DISCOUNTS', 'DIGITAL_BANKING', 'DIGITAL_WALLET', 'DONATE_INTEREST', 'EXTRA_REPAYMENTS', 'FRAUD_PROTECTION', 'FREE_TXNS', 'FREE_TXNS_ALLOWANCE', 'GUARANTOR', 'INSURANCE', 'INSTALMENT_PLAN', 'INTEREST_FREE', 'INTEREST_FREE_TRANSFERS', 'LOYALTY_PROGRAM', 'NOTIFICATIONS', 'NPP_ENABLED', 'NPP_PAYID', 'OFFSET', 'OTHER', 'OVERDRAFT', 'REDRAW', 'RELATIONSHIP_MANAGEMENT', 'UNLIMITED_TXNS')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BankingAccountDetailV3AllOfFeaturesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BankingAccountDetailV3AllOfFeaturesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "featureType": obj.get("featureType"),
            "additionalValue": obj.get("additionalValue"),
            "additionalInfo": obj.get("additionalInfo"),
            "additionalInfoUri": obj.get("additionalInfoUri"),
            "isActivated": obj.get("isActivated") if obj.get("isActivated") is not None else True
        })
        return _obj


