# coding: utf-8

"""
    CDR Banking API

    Consumer Data Standards APIs created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker to meet the needs of the Consumer Data Right

    The version of the OpenAPI document: 1.29.0
    Contact: contact@consumerdatastandards.gov.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from au_open_banking_spec.models.banking_product_discount import BankingProductDiscount
from typing import Optional, Set
from typing_extensions import Self

class BankingProductFee(BaseModel):
    """
    BankingProductFee
    """ # noqa: E501
    name: StrictStr = Field(description="Name of the fee")
    fee_type: StrictStr = Field(description="The type of fee", alias="feeType")
    amount: Optional[StrictStr] = Field(default=None, description="The amount charged for the fee. One of amount, balanceRate, transactionRate and accruedRate is mandatory unless the *feeType* \"VARIABLE\" is supplied")
    balance_rate: Optional[StrictStr] = Field(default=None, description="A fee rate calculated based on a proportion of the balance. One of amount, balanceRate, transactionRate and accruedRate is mandatory unless the *feeType* \"VARIABLE\" is supplied.", alias="balanceRate")
    transaction_rate: Optional[StrictStr] = Field(default=None, description="A fee rate calculated based on a proportion of a transaction. One of amount, balanceRate, transactionRate and accruedRate is mandatory unless the *feeType* \"VARIABLE\" is supplied", alias="transactionRate")
    accrued_rate: Optional[StrictStr] = Field(default=None, description="A fee rate calculated based on a proportion of the calculated interest accrued on the account. One of amount, balanceRate, transactionRate and accruedRate is mandatory unless the *feeType* \"VARIABLE\" is supplied", alias="accruedRate")
    accrual_frequency: Optional[StrictStr] = Field(default=None, description="The indicative frequency with which the fee is calculated on the account. Only applies if balanceRate or accruedRate is also present. Formatted according to [ISO 8601 Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations) (excludes recurrence syntax)", alias="accrualFrequency")
    currency: Optional[StrictStr] = Field(default=None, description="The currency the fee will be charged in. Assumes AUD if absent")
    additional_value: Optional[StrictStr] = Field(default=None, description="Generic field containing additional information relevant to the [feeType](#tocSproductfeetypedoc) specified. Whether mandatory or not is dependent on the value of [feeType](#tocSproductfeetypedoc)", alias="additionalValue")
    additional_info: Optional[StrictStr] = Field(default=None, description="Display text providing more information on the fee", alias="additionalInfo")
    additional_info_uri: Optional[StrictStr] = Field(default=None, description="Link to a web page with more information on this fee", alias="additionalInfoUri")
    discounts: Optional[List[BankingProductDiscount]] = Field(default=None, description="An optional list of discounts to this fee that may be available")
    __properties: ClassVar[List[str]] = ["name", "feeType", "amount", "balanceRate", "transactionRate", "accruedRate", "accrualFrequency", "currency", "additionalValue", "additionalInfo", "additionalInfoUri", "discounts"]

    @field_validator('fee_type')
    def fee_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['DEPOSIT', 'EVENT', 'EXIT', 'PAYMENT', 'PERIODIC', 'PURCHASE', 'TRANSACTION', 'UPFRONT', 'VARIABLE', 'WITHDRAWAL']):
            raise ValueError("must be one of enum values ('DEPOSIT', 'EVENT', 'EXIT', 'PAYMENT', 'PERIODIC', 'PURCHASE', 'TRANSACTION', 'UPFRONT', 'VARIABLE', 'WITHDRAWAL')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BankingProductFee from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in discounts (list)
        _items = []
        if self.discounts:
            for _item in self.discounts:
                if _item:
                    _items.append(_item.to_dict())
            _dict['discounts'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BankingProductFee from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "feeType": obj.get("feeType"),
            "amount": obj.get("amount"),
            "balanceRate": obj.get("balanceRate"),
            "transactionRate": obj.get("transactionRate"),
            "accruedRate": obj.get("accruedRate"),
            "accrualFrequency": obj.get("accrualFrequency"),
            "currency": obj.get("currency"),
            "additionalValue": obj.get("additionalValue"),
            "additionalInfo": obj.get("additionalInfo"),
            "additionalInfoUri": obj.get("additionalInfoUri"),
            "discounts": [BankingProductDiscount.from_dict(_item) for _item in obj["discounts"]] if obj.get("discounts") is not None else None
        })
        return _obj


