# coding: utf-8

"""
    CDR Banking API

    Consumer Data Standards APIs created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker to meet the needs of the Consumer Data Right

    The version of the OpenAPI document: 1.29.0
    Contact: contact@consumerdatastandards.gov.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class BankingProductCategory(str, Enum):
    """
    The category to which a product or account belongs. See [here](#product-categories) for more details
    """

    """
    allowed enum values
    """
    BUSINESS_LOANS = 'BUSINESS_LOANS'
    CRED_AND_CHRG_CARDS = 'CRED_AND_CHRG_CARDS'
    LEASES = 'LEASES'
    MARGIN_LOANS = 'MARGIN_LOANS'
    OVERDRAFTS = 'OVERDRAFTS'
    PERS_LOANS = 'PERS_LOANS'
    REGULATED_TRUST_ACCOUNTS = 'REGULATED_TRUST_ACCOUNTS'
    RESIDENTIAL_MORTGAGES = 'RESIDENTIAL_MORTGAGES'
    TERM_DEPOSITS = 'TERM_DEPOSITS'
    TRADE_FINANCE = 'TRADE_FINANCE'
    TRANS_AND_SAVINGS_ACCOUNTS = 'TRANS_AND_SAVINGS_ACCOUNTS'
    TRAVEL_CARDS = 'TRAVEL_CARDS'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BankingProductCategory from a JSON string"""
        return cls(json.loads(json_str))


