# coding: utf-8

"""
    CDR Banking API

    Consumer Data Standards APIs created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker to meet the needs of the Consumer Data Right

    The version of the OpenAPI document: 1.29.0
    Contact: contact@consumerdatastandards.gov.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from au_open_banking_spec.models.banking_domestic_payee_account import BankingDomesticPayeeAccount
from au_open_banking_spec.models.banking_domestic_payee_card import BankingDomesticPayeeCard
from au_open_banking_spec.models.banking_domestic_payee_pay_id import BankingDomesticPayeePayId
from typing import Optional, Set
from typing_extensions import Self

class BankingDomesticPayee(BaseModel):
    """
    BankingDomesticPayee
    """ # noqa: E501
    payee_account_u_type: StrictStr = Field(description="Type of account object included. Valid values are: **account** A standard Australian account defined by BSB/Account Number. **card** A credit or charge card to pay to (note that PANs are masked). **payId** A PayID recognised by NPP", alias="payeeAccountUType")
    account: Optional[BankingDomesticPayeeAccount] = None
    card: Optional[BankingDomesticPayeeCard] = None
    pay_id: Optional[BankingDomesticPayeePayId] = Field(default=None, alias="payId")
    __properties: ClassVar[List[str]] = ["payeeAccountUType", "account", "card", "payId"]

    @field_validator('payee_account_u_type')
    def payee_account_u_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['account', 'card', 'payId']):
            raise ValueError("must be one of enum values ('account', 'card', 'payId')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BankingDomesticPayee from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of account
        if self.account:
            _dict['account'] = self.account.to_dict()
        # override the default output from pydantic by calling `to_dict()` of card
        if self.card:
            _dict['card'] = self.card.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pay_id
        if self.pay_id:
            _dict['payId'] = self.pay_id.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BankingDomesticPayee from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "payeeAccountUType": obj.get("payeeAccountUType"),
            "account": BankingDomesticPayeeAccount.from_dict(obj["account"]) if obj.get("account") is not None else None,
            "card": BankingDomesticPayeeCard.from_dict(obj["card"]) if obj.get("card") is not None else None,
            "payId": BankingDomesticPayeePayId.from_dict(obj["payId"]) if obj.get("payId") is not None else None
        })
        return _obj


