# coding: utf-8

"""
    CDR Banking API

    Consumer Data Standards APIs created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker to meet the needs of the Consumer Data Right

    The version of the OpenAPI document: 1.29.0
    Contact: contact@consumerdatastandards.gov.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from au_open_banking_spec.models.banking_authorised_entity import BankingAuthorisedEntity
from typing import Optional, Set
from typing_extensions import Self

class BankingDirectDebit(BaseModel):
    """
    BankingDirectDebit
    """ # noqa: E501
    account_id: StrictStr = Field(description="A unique ID of the account adhering to the standards for ID permanence.", alias="accountId")
    authorised_entity: BankingAuthorisedEntity = Field(alias="authorisedEntity")
    last_debit_date_time: Optional[StrictStr] = Field(default=None, description="The date and time of the last debit executed under this authorisation", alias="lastDebitDateTime")
    last_debit_amount: Optional[StrictStr] = Field(default=None, description="The amount of the last debit executed under this authorisation", alias="lastDebitAmount")
    __properties: ClassVar[List[str]] = ["accountId", "authorisedEntity", "lastDebitDateTime", "lastDebitAmount"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BankingDirectDebit from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of authorised_entity
        if self.authorised_entity:
            _dict['authorisedEntity'] = self.authorised_entity.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BankingDirectDebit from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accountId": obj.get("accountId"),
            "authorisedEntity": BankingAuthorisedEntity.from_dict(obj["authorisedEntity"]) if obj.get("authorisedEntity") is not None else None,
            "lastDebitDateTime": obj.get("lastDebitDateTime"),
            "lastDebitAmount": obj.get("lastDebitAmount")
        })
        return _obj


