# coding: utf-8

"""
    CDR Banking API

    Consumer Data Standards APIs created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker to meet the needs of the Consumer Data Right

    The version of the OpenAPI document: 1.29.0
    Contact: contact@consumerdatastandards.gov.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from au_open_banking_spec.models.common_paf_address import CommonPAFAddress
from au_open_banking_spec.models.common_simple_address import CommonSimpleAddress
from typing import Optional, Set
from typing_extensions import Self

class CommonPhysicalAddress(BaseModel):
    """
    CommonPhysicalAddress
    """ # noqa: E501
    address_u_type: StrictStr = Field(description="The type of address object present", alias="addressUType")
    simple: Optional[CommonSimpleAddress] = None
    paf: Optional[CommonPAFAddress] = None
    __properties: ClassVar[List[str]] = ["addressUType", "simple", "paf"]

    @field_validator('address_u_type')
    def address_u_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['paf', 'simple']):
            raise ValueError("must be one of enum values ('paf', 'simple')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CommonPhysicalAddress from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of simple
        if self.simple:
            _dict['simple'] = self.simple.to_dict()
        # override the default output from pydantic by calling `to_dict()` of paf
        if self.paf:
            _dict['paf'] = self.paf.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CommonPhysicalAddress from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "addressUType": obj.get("addressUType"),
            "simple": CommonSimpleAddress.from_dict(obj["simple"]) if obj.get("simple") is not None else None,
            "paf": CommonPAFAddress.from_dict(obj["paf"]) if obj.get("paf") is not None else None
        })
        return _obj


