# coding: utf-8

"""
    CDR Banking API

    Consumer Data Standards APIs created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker to meet the needs of the Consumer Data Right

    The version of the OpenAPI document: 1.29.0
    Contact: contact@consumerdatastandards.gov.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field
from typing import Any, ClassVar, Dict, List
from au_open_banking_spec.models.banking_scheduled_payment_v2 import BankingScheduledPaymentV2
from typing import Optional, Set
from typing_extensions import Self

class ResponseBankingScheduledPaymentsListV2Data(BaseModel):
    """
    ResponseBankingScheduledPaymentsListV2Data
    """ # noqa: E501
    scheduled_payments: List[BankingScheduledPaymentV2] = Field(description="The list of scheduled payments to return", alias="scheduledPayments")
    __properties: ClassVar[List[str]] = ["scheduledPayments"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResponseBankingScheduledPaymentsListV2Data from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in scheduled_payments (list)
        _items = []
        if self.scheduled_payments:
            for _item in self.scheduled_payments:
                if _item:
                    _items.append(_item.to_dict())
            _dict['scheduledPayments'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResponseBankingScheduledPaymentsListV2Data from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "scheduledPayments": [BankingScheduledPaymentV2.from_dict(_item) for _item in obj["scheduledPayments"]] if obj.get("scheduledPayments") is not None else None
        })
        return _obj


