# coding: utf-8

"""
    CDR Banking API

    Consumer Data Standards APIs created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker to meet the needs of the Consumer Data Right

    The version of the OpenAPI document: 1.29.0
    Contact: contact@consumerdatastandards.gov.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from au_open_banking_spec.models.banking_scheduled_payment_v2 import BankingScheduledPaymentV2

class TestBankingScheduledPaymentV2(unittest.TestCase):
    """BankingScheduledPaymentV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BankingScheduledPaymentV2:
        """Test BankingScheduledPaymentV2
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BankingScheduledPaymentV2`
        """
        model = BankingScheduledPaymentV2()
        if include_optional:
            return BankingScheduledPaymentV2(
                scheduled_payment_id = '',
                nickname = '',
                payer_reference = '',
                payee_reference = '',
                status = 'ACTIVE',
                var_from = {"accountId":"accountId"},
                payment_set = [
                    {"isAmountCalculated":true,"amount":"amount","currency":"currency","to":{"domestic":{"payeeAccountUType":"account","payId":{"identifier":"identifier","name":"name","type":"ABN"},"account":{"bsb":"bsb","accountName":"accountName","accountNumber":"accountNumber"},"card":{"cardNumber":"cardNumber"}},"accountId":"accountId","biller":{"billerName":"billerName","crn":"crn","billerCode":"billerCode"},"digitalWallet":{"identifier":"identifier","provider":"PAYPAL_AU","name":"name","type":"EMAIL"},"payeeReference":"payeeReference","toUType":"accountId","nickname":"nickname","payeeId":"payeeId","international":{"bankDetails":{"country":"country","routingNumber":"routingNumber","fedWireNumber":"fedWireNumber","chipNumber":"chipNumber","legalEntityIdentifier":"legalEntityIdentifier","accountNumber":"accountNumber","bankAddress":{"address":"address","name":"name"},"sortCode":"sortCode","beneficiaryBankBIC":"beneficiaryBankBIC"},"beneficiaryDetails":{"country":"country","name":"name","message":"message"}}}}
                    ],
                recurrence = {"nextPaymentDate":"nextPaymentDate","eventBased":{"description":"description"},"onceOff":{"paymentDate":"paymentDate"},"recurrenceUType":"eventBased","intervalSchedule":{"intervals":[{"interval":"interval","dayInInterval":"dayInInterval"},{"interval":"interval","dayInInterval":"dayInInterval"}],"paymentsRemaining":1,"finalPaymentDate":"finalPaymentDate","nonBusinessDayTreatment":"ON"},"lastWeekDay":{"paymentsRemaining":1,"interval":"interval","finalPaymentDate":"finalPaymentDate","lastWeekDay":"FRI","nonBusinessDayTreatment":"ON"}}
            )
        else:
            return BankingScheduledPaymentV2(
                scheduled_payment_id = '',
                payer_reference = '',
                status = 'ACTIVE',
                var_from = {"accountId":"accountId"},
                payment_set = [
                    {"isAmountCalculated":true,"amount":"amount","currency":"currency","to":{"domestic":{"payeeAccountUType":"account","payId":{"identifier":"identifier","name":"name","type":"ABN"},"account":{"bsb":"bsb","accountName":"accountName","accountNumber":"accountNumber"},"card":{"cardNumber":"cardNumber"}},"accountId":"accountId","biller":{"billerName":"billerName","crn":"crn","billerCode":"billerCode"},"digitalWallet":{"identifier":"identifier","provider":"PAYPAL_AU","name":"name","type":"EMAIL"},"payeeReference":"payeeReference","toUType":"accountId","nickname":"nickname","payeeId":"payeeId","international":{"bankDetails":{"country":"country","routingNumber":"routingNumber","fedWireNumber":"fedWireNumber","chipNumber":"chipNumber","legalEntityIdentifier":"legalEntityIdentifier","accountNumber":"accountNumber","bankAddress":{"address":"address","name":"name"},"sortCode":"sortCode","beneficiaryBankBIC":"beneficiaryBankBIC"},"beneficiaryDetails":{"country":"country","name":"name","message":"message"}}}}
                    ],
                recurrence = {"nextPaymentDate":"nextPaymentDate","eventBased":{"description":"description"},"onceOff":{"paymentDate":"paymentDate"},"recurrenceUType":"eventBased","intervalSchedule":{"intervals":[{"interval":"interval","dayInInterval":"dayInInterval"},{"interval":"interval","dayInInterval":"dayInInterval"}],"paymentsRemaining":1,"finalPaymentDate":"finalPaymentDate","nonBusinessDayTreatment":"ON"},"lastWeekDay":{"paymentsRemaining":1,"interval":"interval","finalPaymentDate":"finalPaymentDate","lastWeekDay":"FRI","nonBusinessDayTreatment":"ON"}},
        )
        """

    def testBankingScheduledPaymentV2(self):
        """Test BankingScheduledPaymentV2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
