# coding: utf-8

"""
    CDR Banking API

    Consumer Data Standards APIs created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker to meet the needs of the Consumer Data Right

    The version of the OpenAPI document: 1.29.0
    Contact: contact@consumerdatastandards.gov.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from au_open_banking_spec.api.banking_api import BankingApi


class TestBankingApi(unittest.TestCase):
    """BankingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BankingApi()

    def tearDown(self) -> None:
        pass

    def test_get_account_detail(self) -> None:
        """Test case for get_account_detail

        Get Account Detail
        """
        pass

    def test_get_balance(self) -> None:
        """Test case for get_balance

        Get Account Balance
        """
        pass

    def test_get_payee_detail(self) -> None:
        """Test case for get_payee_detail

        Get Payee Detail
        """
        pass

    def test_get_product_detail(self) -> None:
        """Test case for get_product_detail

        Get Product Detail
        """
        pass

    def test_get_transaction_detail(self) -> None:
        """Test case for get_transaction_detail

        Get Transaction Detail
        """
        pass

    def test_get_transactions(self) -> None:
        """Test case for get_transactions

        Get Transactions For Account
        """
        pass

    def test_list_accounts(self) -> None:
        """Test case for list_accounts

        Get Accounts
        """
        pass

    def test_list_balances_bulk(self) -> None:
        """Test case for list_balances_bulk

        Get Bulk Balances
        """
        pass

    def test_list_balances_specific_accounts(self) -> None:
        """Test case for list_balances_specific_accounts

        Get Balances For Specific Accounts
        """
        pass

    def test_list_direct_debits(self) -> None:
        """Test case for list_direct_debits

        Get Direct Debits For Account
        """
        pass

    def test_list_direct_debits_bulk(self) -> None:
        """Test case for list_direct_debits_bulk

        Get Bulk Direct Debits
        """
        pass

    def test_list_direct_debits_specific_accounts(self) -> None:
        """Test case for list_direct_debits_specific_accounts

        Get Direct Debits For Specific Accounts
        """
        pass

    def test_list_payees(self) -> None:
        """Test case for list_payees

        Get Payees
        """
        pass

    def test_list_products(self) -> None:
        """Test case for list_products

        Get Products
        """
        pass

    def test_list_scheduled_payments(self) -> None:
        """Test case for list_scheduled_payments

        Get Scheduled Payments for Account
        """
        pass

    def test_list_scheduled_payments_bulk(self) -> None:
        """Test case for list_scheduled_payments_bulk

        Get Scheduled Payments Bulk
        """
        pass

    def test_list_scheduled_payments_specific_accounts(self) -> None:
        """Test case for list_scheduled_payments_specific_accounts

        Get Scheduled Payments For Specific Accounts
        """
        pass


if __name__ == '__main__':
    unittest.main()
