# coding: utf-8

"""
    CDR Banking API

    Consumer Data Standards APIs created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker to meet the needs of the Consumer Data Right

    The version of the OpenAPI document: 1.29.0
    Contact: contact@consumerdatastandards.gov.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from au_open_banking_spec.api.payees_api import PayeesApi


class TestPayeesApi(unittest.TestCase):
    """PayeesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PayeesApi()

    def tearDown(self) -> None:
        pass

    def test_get_payee_detail(self) -> None:
        """Test case for get_payee_detail

        Get Payee Detail
        """
        pass

    def test_list_payees(self) -> None:
        """Test case for list_payees

        Get Payees
        """
        pass


if __name__ == '__main__':
    unittest.main()
