# coding: utf-8

"""
    CDR Banking API

    Consumer Data Standards APIs created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker to meet the needs of the Consumer Data Right

    The version of the OpenAPI document: 1.29.0
    Contact: contact@consumerdatastandards.gov.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from au_open_banking_spec.api.scheduled_payments_api import ScheduledPaymentsApi


class TestScheduledPaymentsApi(unittest.TestCase):
    """ScheduledPaymentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ScheduledPaymentsApi()

    def tearDown(self) -> None:
        pass

    def test_list_scheduled_payments(self) -> None:
        """Test case for list_scheduled_payments

        Get Scheduled Payments for Account
        """
        pass

    def test_list_scheduled_payments_bulk(self) -> None:
        """Test case for list_scheduled_payments_bulk

        Get Scheduled Payments Bulk
        """
        pass

    def test_list_scheduled_payments_specific_accounts(self) -> None:
        """Test case for list_scheduled_payments_specific_accounts

        Get Scheduled Payments For Specific Accounts
        """
        pass


if __name__ == '__main__':
    unittest.main()
