# coding: utf-8

"""
    CDR Banking API

    Consumer Data Standards APIs created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker to meet the needs of the Consumer Data Right

    The version of the OpenAPI document: 1.29.0
    Contact: contact@consumerdatastandards.gov.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from au_open_banking_spec.models.response_banking_transaction_list import ResponseBankingTransactionList

class TestResponseBankingTransactionList(unittest.TestCase):
    """ResponseBankingTransactionList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseBankingTransactionList:
        """Test ResponseBankingTransactionList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseBankingTransactionList`
        """
        model = ResponseBankingTransactionList()
        if include_optional:
            return ResponseBankingTransactionList(
                data = {"transactions":[{"postingDateTime":"postingDateTime","amount":"amount","apcaNumber":"apcaNumber","isDetailAvailable":true,"description":"description","type":"DIRECT_DEBIT","billerName":"billerName","executionDateTime":"executionDateTime","transactionId":"transactionId","merchantName":"merchantName","billerCode":"billerCode","reference":"reference","accountId":"accountId","merchantCategoryCode":"merchantCategoryCode","valueDateTime":"valueDateTime","currency":"currency","crn":"crn","status":"PENDING"},{"postingDateTime":"postingDateTime","amount":"amount","apcaNumber":"apcaNumber","isDetailAvailable":true,"description":"description","type":"DIRECT_DEBIT","billerName":"billerName","executionDateTime":"executionDateTime","transactionId":"transactionId","merchantName":"merchantName","billerCode":"billerCode","reference":"reference","accountId":"accountId","merchantCategoryCode":"merchantCategoryCode","valueDateTime":"valueDateTime","currency":"currency","crn":"crn","status":"PENDING"}]},
                links = {"next":"next","last":"last","prev":"prev","self":"self","first":"first"},
                meta = None
            )
        else:
            return ResponseBankingTransactionList(
                data = {"transactions":[{"postingDateTime":"postingDateTime","amount":"amount","apcaNumber":"apcaNumber","isDetailAvailable":true,"description":"description","type":"DIRECT_DEBIT","billerName":"billerName","executionDateTime":"executionDateTime","transactionId":"transactionId","merchantName":"merchantName","billerCode":"billerCode","reference":"reference","accountId":"accountId","merchantCategoryCode":"merchantCategoryCode","valueDateTime":"valueDateTime","currency":"currency","crn":"crn","status":"PENDING"},{"postingDateTime":"postingDateTime","amount":"amount","apcaNumber":"apcaNumber","isDetailAvailable":true,"description":"description","type":"DIRECT_DEBIT","billerName":"billerName","executionDateTime":"executionDateTime","transactionId":"transactionId","merchantName":"merchantName","billerCode":"billerCode","reference":"reference","accountId":"accountId","merchantCategoryCode":"merchantCategoryCode","valueDateTime":"valueDateTime","currency":"currency","crn":"crn","status":"PENDING"}]},
                links = {"next":"next","last":"last","prev":"prev","self":"self","first":"first"},
                meta = None,
        )
        """

    def testResponseBankingTransactionList(self):
        """Test ResponseBankingTransactionList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
