# coding: utf-8

"""
    CDR Banking API

    Consumer Data Standards APIs created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker to meet the needs of the Consumer Data Right

    The version of the OpenAPI document: 1.29.0
    Contact: contact@consumerdatastandards.gov.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from au_open_banking_spec.api.accounts_api import AccountsApi


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountsApi()

    def tearDown(self) -> None:
        pass

    def test_get_account_detail(self) -> None:
        """Test case for get_account_detail

        Get Account Detail
        """
        pass

    def test_get_balance(self) -> None:
        """Test case for get_balance

        Get Account Balance
        """
        pass

    def test_get_transaction_detail(self) -> None:
        """Test case for get_transaction_detail

        Get Transaction Detail
        """
        pass

    def test_get_transactions(self) -> None:
        """Test case for get_transactions

        Get Transactions For Account
        """
        pass

    def test_list_accounts(self) -> None:
        """Test case for list_accounts

        Get Accounts
        """
        pass

    def test_list_balances_bulk(self) -> None:
        """Test case for list_balances_bulk

        Get Bulk Balances
        """
        pass

    def test_list_balances_specific_accounts(self) -> None:
        """Test case for list_balances_specific_accounts

        Get Balances For Specific Accounts
        """
        pass


if __name__ == '__main__':
    unittest.main()
