# coding: utf-8

"""
    CDR Banking API

    Consumer Data Standards APIs created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker to meet the needs of the Consumer Data Right

    The version of the OpenAPI document: 1.29.0
    Contact: contact@consumerdatastandards.gov.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from au_open_banking_spec.models.banking_scheduled_payment_recurrence_last_weekday import BankingScheduledPaymentRecurrenceLastWeekday

class TestBankingScheduledPaymentRecurrenceLastWeekday(unittest.TestCase):
    """BankingScheduledPaymentRecurrenceLastWeekday unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BankingScheduledPaymentRecurrenceLastWeekday:
        """Test BankingScheduledPaymentRecurrenceLastWeekday
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BankingScheduledPaymentRecurrenceLastWeekday`
        """
        model = BankingScheduledPaymentRecurrenceLastWeekday()
        if include_optional:
            return BankingScheduledPaymentRecurrenceLastWeekday(
                final_payment_date = '',
                payments_remaining = 1,
                interval = '',
                last_week_day = 'FRI',
                non_business_day_treatment = 'ON'
            )
        else:
            return BankingScheduledPaymentRecurrenceLastWeekday(
                interval = '',
                last_week_day = 'FRI',
        )
        """

    def testBankingScheduledPaymentRecurrenceLastWeekday(self):
        """Test BankingScheduledPaymentRecurrenceLastWeekday"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
