# coding: utf-8

"""
    CDR Banking API

    Consumer Data Standards APIs created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker to meet the needs of the Consumer Data Right

    The version of the OpenAPI document: 1.29.0
    Contact: contact@consumerdatastandards.gov.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from au_open_banking_spec.models.response_banking_account_by_id_v3 import ResponseBankingAccountByIdV3

class TestResponseBankingAccountByIdV3(unittest.TestCase):
    """ResponseBankingAccountByIdV3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseBankingAccountByIdV3:
        """Test ResponseBankingAccountByIdV3
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseBankingAccountByIdV3`
        """
        model = ResponseBankingAccountByIdV3()
        if include_optional:
            return ResponseBankingAccountByIdV3(
                data = None,
                links = {"self":"self"},
                meta = None
            )
        else:
            return ResponseBankingAccountByIdV3(
                data = None,
                links = {"self":"self"},
        )
        """

    def testResponseBankingAccountByIdV3(self):
        """Test ResponseBankingAccountByIdV3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
