# coding: utf-8

"""
    CDR Banking API

    Consumer Data Standards APIs created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker to meet the needs of the Consumer Data Right

    The version of the OpenAPI document: 1.29.0
    Contact: contact@consumerdatastandards.gov.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from au_open_banking_spec.models.banking_transaction import BankingTransaction

class TestBankingTransaction(unittest.TestCase):
    """BankingTransaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BankingTransaction:
        """Test BankingTransaction
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BankingTransaction`
        """
        model = BankingTransaction()
        if include_optional:
            return BankingTransaction(
                account_id = '',
                transaction_id = '',
                is_detail_available = True,
                type = 'DIRECT_DEBIT',
                status = 'PENDING',
                description = '',
                posting_date_time = '',
                value_date_time = '',
                execution_date_time = '',
                amount = '',
                currency = '',
                reference = '',
                merchant_name = '',
                merchant_category_code = '',
                biller_code = '',
                biller_name = '',
                crn = '',
                apca_number = ''
            )
        else:
            return BankingTransaction(
                account_id = '',
                is_detail_available = True,
                type = 'DIRECT_DEBIT',
                status = 'PENDING',
                description = '',
                amount = '',
                reference = '',
        )
        """

    def testBankingTransaction(self):
        """Test BankingTransaction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
