# coding: utf-8

"""
    CDR Banking API

    Consumer Data Standards APIs created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker to meet the needs of the Consumer Data Right

    The version of the OpenAPI document: 1.29.0
    Contact: contact@consumerdatastandards.gov.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from au_open_banking_spec.models.response_banking_account_list_v2 import ResponseBankingAccountListV2

class TestResponseBankingAccountListV2(unittest.TestCase):
    """ResponseBankingAccountListV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseBankingAccountListV2:
        """Test ResponseBankingAccountListV2
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseBankingAccountListV2`
        """
        model = ResponseBankingAccountListV2()
        if include_optional:
            return ResponseBankingAccountListV2(
                data = {"accounts":[{"accountId":"accountId","maskedNumber":"maskedNumber","openStatus":"OPEN","displayName":"displayName","isOwned":true,"nickname":"nickname","creationDate":"creationDate","productName":"productName","accountOwnership":"UNKNOWN"},{"accountId":"accountId","maskedNumber":"maskedNumber","openStatus":"OPEN","displayName":"displayName","isOwned":true,"nickname":"nickname","creationDate":"creationDate","productName":"productName","accountOwnership":"UNKNOWN"}]},
                links = {"next":"next","last":"last","prev":"prev","self":"self","first":"first"},
                meta = {"totalRecords":0,"totalPages":6}
            )
        else:
            return ResponseBankingAccountListV2(
                data = {"accounts":[{"accountId":"accountId","maskedNumber":"maskedNumber","openStatus":"OPEN","displayName":"displayName","isOwned":true,"nickname":"nickname","creationDate":"creationDate","productName":"productName","accountOwnership":"UNKNOWN"},{"accountId":"accountId","maskedNumber":"maskedNumber","openStatus":"OPEN","displayName":"displayName","isOwned":true,"nickname":"nickname","creationDate":"creationDate","productName":"productName","accountOwnership":"UNKNOWN"}]},
                links = {"next":"next","last":"last","prev":"prev","self":"self","first":"first"},
                meta = {"totalRecords":0,"totalPages":6},
        )
        """

    def testResponseBankingAccountListV2(self):
        """Test ResponseBankingAccountListV2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
