# coding: utf-8

"""
    CDR Banking API

    Consumer Data Standards APIs created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker to meet the needs of the Consumer Data Right

    The version of the OpenAPI document: 1.29.0
    Contact: contact@consumerdatastandards.gov.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from au_open_banking_spec.models.banking_transaction_detail_all_of_extended_data import BankingTransactionDetailAllOfExtendedData

class TestBankingTransactionDetailAllOfExtendedData(unittest.TestCase):
    """BankingTransactionDetailAllOfExtendedData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BankingTransactionDetailAllOfExtendedData:
        """Test BankingTransactionDetailAllOfExtendedData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BankingTransactionDetailAllOfExtendedData`
        """
        model = BankingTransactionDetailAllOfExtendedData()
        if include_optional:
            return BankingTransactionDetailAllOfExtendedData(
                payer = '',
                payee = '',
                extension_u_type = 'x2p101Payload',
                x2p101_payload = au_open_banking_spec.models.banking_transaction_detail_all_of_extended_data_x2p101_payload.BankingTransactionDetail_allOf_extendedData_x2p101Payload(
                    extended_description = '', 
                    end_to_end_id = '', 
                    purpose_code = '', ),
                service = 'X2P1.01'
            )
        else:
            return BankingTransactionDetailAllOfExtendedData(
                service = 'X2P1.01',
        )
        """

    def testBankingTransactionDetailAllOfExtendedData(self):
        """Test BankingTransactionDetailAllOfExtendedData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
